import { Category, Product, ProductImage } from '@/types/database';

// Dados mock para funcionar sem Supabase - Alto Mar Aquarismo
// Referência: catálogo de corais e peixes marinhos

export const MOCK_CATEGORIES: Category[] = [
    { id: '1', name: 'Corais Moles', slug: 'corais-moles', icon: 'spa', sort_order: 0, active: true, created_at: new Date().toISOString() },
    { id: '2', name: 'Corais Duros (LPS)', slug: 'corais-lps', icon: 'diamond', sort_order: 1, active: true, created_at: new Date().toISOString() },
    { id: '3', name: 'Corais Duros (SPS)', slug: 'corais-sps', icon: 'hexagon', sort_order: 2, active: true, created_at: new Date().toISOString() },
    { id: '4', name: 'Peixes Marinhos', slug: 'peixes-marinhos', icon: 'phishing', sort_order: 3, active: true, created_at: new Date().toISOString() },
    { id: '5', name: 'Invertebrados', slug: 'invertebrados', icon: 'bug_report', sort_order: 4, active: true, created_at: new Date().toISOString() },
    { id: '6', name: 'Equipamentos', slug: 'equipamentos', icon: 'settings', sort_order: 5, active: true, created_at: new Date().toISOString() },
];

export const MOCK_IMAGES: ProductImage[] = [
    { id: 'img-powder', product_id: 'p1', url: 'https://images.unsplash.com/photo-1535591273668-578e31182c4f?q=80&w=800', sort_order: 0, is_main: true },
    { id: 'img-hepatus', product_id: 'p2', url: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=800', sort_order: 0, is_main: true },
    { id: 'img-desjardini', product_id: 'p3', url: 'https://images.unsplash.com/photo-1522069169874-c58ec4b76be5?q=80&w=800', sort_order: 0, is_main: true },
    { id: 'img-yellow', product_id: 'p4', url: 'https://images.unsplash.com/photo-1524704654690-b56c05c78a00?q=80&w=800', sort_order: 0, is_main: true },
    { id: 'img-achilles', product_id: 'p5', url: 'https://images.unsplash.com/photo-1501504905252-473c47e087f8?q=80&w=800', sort_order: 0, is_main: true },
    { id: 'img-black', product_id: 'p6', url: 'https://images.unsplash.com/photo-1535591273668-578e31182c4f?q=80&w=800', sort_order: 0, is_main: true },
    { id: 'img-purple', product_id: 'p7', url: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=800', sort_order: 0, is_main: true },
    { id: 'img-scolymia', product_id: 'p8', url: 'https://images.unsplash.com/photo-1546027658-7aa750153465?q=80&w=800', sort_order: 0, is_main: true },
    { id: 'img-torch-ds', product_id: 'p9', url: 'https://images.unsplash.com/photo-1546027658-7aa750153465?q=80&w=800', sort_order: 0, is_main: true },
    { id: 'img-torch-24k', product_id: 'p10', url: 'https://images.unsplash.com/photo-1546027658-7aa750153465?q=80&w=800', sort_order: 0, is_main: true },
    { id: 'img-hammer', product_id: 'p11', url: 'https://images.unsplash.com/photo-1546027658-7aa750153465?q=80&w=800', sort_order: 0, is_main: true },
    { id: 'img-holy-grail', product_id: 'p12', url: 'https://images.unsplash.com/photo-1546027658-7aa750153465?q=80&w=800', sort_order: 0, is_main: true },
    { id: 'img-gemmatum', product_id: 'p13', url: 'https://images.unsplash.com/photo-1535591273668-578e31182c4f?q=80&w=800', sort_order: 0, is_main: true },
    { id: 'img-anthias', product_id: 'p14', url: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=800', sort_order: 0, is_main: true },
    { id: 'img-goniopora-red', product_id: 'p15', url: 'https://images.unsplash.com/photo-1546027658-7aa750153465?q=80&w=800', sort_order: 0, is_main: true },
    { id: 'img-alveopora', product_id: 'p16', url: 'https://images.unsplash.com/photo-1546027658-7aa750153465?q=80&w=800', sort_order: 0, is_main: true },
    { id: 'img-chalice', product_id: 'p17', url: 'https://images.unsplash.com/photo-1546027658-7aa750153465?q=80&w=800', sort_order: 0, is_main: true },
    { id: 'img-yuma', product_id: 'p18', url: 'https://images.unsplash.com/photo-1546027658-7aa750153465?q=80&w=800', sort_order: 0, is_main: true },
    { id: 'img-mushroom', product_id: 'p19', url: 'https://images.unsplash.com/photo-1546027658-7aa750153465?q=80&w=800', sort_order: 0, is_main: true },
];

export const MOCK_PRODUCTS: Product[] = [
    {
        id: 'p1', name: 'Tang Powder Blue', slug: 'tang-powder-blue-g', code: 'PEI-001',
        description: 'Acanthurus leucosternon, o famoso Tang Powder Blue. Peixe ativo e de coloração azul vibrante. Requer aquário estabelecido e com espaço para nado. Tamanho G.',
        price: 690.00, min_quantity: 1, category_id: '4', status: 'active', featured: true, tag: 'Destaque',
        production_time: 'Pronta Entrega', click_count: 85, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        category: undefined,
        images: [MOCK_IMAGES[0]],
    },
    {
        id: 'p2', name: 'Hepatus (Dory)', slug: 'hepatus-dory-m', code: 'PEI-002',
        description: 'Paracanthurus hepatus, conhecido como Blue Tang ou Dory. Coloração azul intensa com marcações pretas. Essencial para aquários de recife. Tamanho M.',
        price: 590.00, min_quantity: 1, category_id: '4', status: 'active', featured: true, tag: 'Popular',
        production_time: 'Pronta Entrega', click_count: 120, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        category: undefined,
        images: [MOCK_IMAGES[1]],
    },
    {
        id: 'p3', name: 'Tang Desjardini', slug: 'tang-desjardini-g', code: 'PEI-003',
        description: 'Zebrasoma desjardinii, Sailfin Tang. Padrão de cores impressionante e barbatanas majestosas. Ótimo para controle de algas. Tamanho G.',
        price: 790.00, min_quantity: 1, category_id: '4', status: 'active', featured: false, tag: null,
        production_time: 'Pronta Entrega', click_count: 55, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        category: undefined,
        images: [MOCK_IMAGES[2]],
    },
    {
        id: 'p4', name: 'Yellow Tang Hawaii (Desmonte)', slug: 'yellow-tang-hawaii', code: 'PEI-004',
        description: 'Zebrasoma flavescens, o clássico Yellow Tang de Hawaii. Cor amarelo sólido radiante. Peixe muito resistente e ativo. Oriundo de desmonte.',
        price: 4500.00, min_quantity: 1, category_id: '4', status: 'active', featured: true, tag: 'Raro',
        production_time: 'Pronta Entrega', click_count: 95, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        category: undefined,
        images: [MOCK_IMAGES[3]],
    },
    {
        id: 'p5', name: 'Tang Achilles', slug: 'tang-achilles-g', code: 'PEI-005',
        description: 'Acanthurus achilles. Um dos peixes mais desejados do aquarismo marinho. Corpo preto aveludado com mancha laranja distintiva. Tamanho G.',
        price: 5999.00, min_quantity: 1, category_id: '4', status: 'active', featured: true, tag: 'Premium',
        production_time: 'Pronta Entrega', click_count: 70, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        category: undefined,
        images: [MOCK_IMAGES[4]],
    },
    {
        id: 'p6', name: 'Black Tang', slug: 'black-tang-g', code: 'PEI-006',
        description: 'Zebrasoma rostratum, Black Tang. Uma espécie rara e exótica, totalmente preta com focinho alongado. Para colecionadores. Tamanho G.',
        price: 15000.00, min_quantity: 1, category_id: '4', status: 'active', featured: true, tag: 'Exótico',
        production_time: 'Pronta Entrega', click_count: 150, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        category: undefined,
        images: [MOCK_IMAGES[5]],
    },
    {
        id: 'p7', name: 'Purple Tang', slug: 'purple-tang-g', code: 'PEI-007',
        description: 'Zebrasoma xanthurum, Purple Tang. Coloração roxa profunda com cauda amarela vibrante. Muito territorial e belíssimo. Tamanho G.',
        price: 990.00, min_quantity: 1, category_id: '4', status: 'active', featured: false, tag: null,
        production_time: 'Pronta Entrega', click_count: 65, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        category: undefined,
        images: [MOCK_IMAGES[6]],
    },
    {
        id: 'p13', name: 'Tang Gemmatum', slug: 'tang-gemmatum-g', code: 'PEI-008',
        description: 'Zebrasoma gemmatum. Peixe extremamente raro e valorizado, com corpo preto e manchas brancas tipo cristais. Tamanho G.',
        price: 4500.00, min_quantity: 1, category_id: '4', status: 'active', featured: true, tag: 'Raridade',
        production_time: 'Pronta Entrega', click_count: 110, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        category: undefined,
        images: [MOCK_IMAGES[12]],
    },
    {
        id: 'p8', name: 'Scolymia de Manto Grande - A', slug: 'scolymia-manto-grande-a', code: 'LPS-001',
        description: 'Scolymia australis de padrão Premium. Cores vibrantes e anéis perfeitos. Coral LPS central de altíssimo valor ornamental.',
        price: 3499.00, min_quantity: 1, category_id: '2', status: 'active', featured: true, tag: 'Mestre',
        production_time: 'Pronta Entrega', click_count: 40, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        category: undefined,
        images: [MOCK_IMAGES[7]],
    },
    {
        id: 'p9', name: 'Torch Dragon Soul (Colônia)', slug: 'torch-dragon-soul-colonia', code: 'LPS-002',
        description: 'Euphyllia glabrescens Dragon Soul. Colônia com múltiplos pólipos exibindo cores douradas e esverdeadas intensas.',
        price: 1959.00, min_quantity: 1, category_id: '2', status: 'active', featured: true, tag: 'Esgotando',
        production_time: 'Pronta Entrega', click_count: 60, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        category: undefined,
        images: [MOCK_IMAGES[8]],
    },
    {
        id: 'p10', name: 'Torch 24K (Colônia)', slug: 'torch-24k-colonia', code: 'LPS-003',
        description: 'Euphyllia glabrescens 24K Gold. Tentáculos dourados brilhantes que balançam com o fluxo de água. Um dos toches mais cobiçados.',
        price: 1959.00, min_quantity: 1, category_id: '2', status: 'active', featured: true, tag: 'Promoção',
        production_time: 'Pronta Entrega', click_count: 80, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        category: undefined,
        images: [MOCK_IMAGES[9]],
    },
    {
        id: 'p11', name: 'Hammer Wall Gold', slug: 'hammer-wall-gold', code: 'LPS-004',
        description: 'Euphyllia ancora Wall Gold. Coral de crescimento lateral com coloração dourada metalizada e padrões tipo martelo.',
        price: 2399.00, min_quantity: 1, category_id: '2', status: 'active', featured: false, tag: null,
        production_time: 'Pronta Entrega', click_count: 35, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        category: undefined,
        images: [MOCK_IMAGES[10]],
    },
    {
        id: 'p12', name: 'Torch Holy Grail', slug: 'torch-holy-grail', code: 'LPS-005',
        description: 'Euphyllia glabrescens Holy Grail. O Santo Graal dos corais Torch. Padrões de cores neon verdes e douradas com pontas azuis.',
        price: 1100.00, min_quantity: 1, category_id: '2', status: 'active', featured: true, tag: 'Santo Graal',
        production_time: 'Pronta Entrega', click_count: 110, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        category: undefined,
        images: [MOCK_IMAGES[11]],
    },
    {
        id: 'p15', name: 'Goniopora Red', slug: 'goniopora-red', code: 'LPS-006',
        description: 'Goniopora de coloração vermelha intensa. Um coral vibrante que adiciona movimento e cor única ao aquário.',
        price: 499.00, min_quantity: 1, category_id: '2', status: 'active', featured: false, tag: 'Vibrante',
        production_time: 'Pronta Entrega', click_count: 45, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        category: undefined,
        images: [MOCK_IMAGES[14]],
    },
    {
        id: 'p16', name: 'Alveopora Green Neon', slug: 'alveopora-green-neon', code: 'LPS-007',
        description: 'Alveopora com coloração verde neon. Semelhante à Goniopora mas com 12 tentáculos por pólipo. Muito delicada e bela.',
        price: 839.00, min_quantity: 1, category_id: '2', status: 'active', featured: false, tag: null,
        production_time: 'Pronta Entrega', click_count: 30, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        category: undefined,
        images: [MOCK_IMAGES[15]],
    },
    {
        id: 'p17', name: 'Chalice Smooth Orange', slug: 'chalice-smooth-orange', code: 'LPS-008',
        description: 'Coral Chalice de coloração laranja suave e textura lisa. Cresce em formato de prato, adicionando estrutura ao layout.',
        price: 1259.00, min_quantity: 1, category_id: '2', status: 'active', featured: true, tag: 'Destaque',
        production_time: 'Pronta Entrega', click_count: 38, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        category: undefined,
        images: [MOCK_IMAGES[16]],
    },
    {
        id: 'p18', name: 'Ricordea Yuma Orange', slug: 'ricordea-yuma-orange', code: 'SOFT-001',
        description: 'Ricordea Yuma de coloração laranja neon. Coral mole de fácil manutenção e visual impactante.',
        price: 1190.00, min_quantity: 1, category_id: '1', status: 'active', featured: true, tag: 'Coleção',
        production_time: 'Pronta Entrega', click_count: 52, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        category: undefined,
        images: [MOCK_IMAGES[17]],
    },
    {
        id: 'p19', name: 'Mushroom Rhodactis Ultra Grade', slug: 'mushroom-rhodactis-ultra', code: 'SOFT-002',
        description: 'Mushroom Rhodactis de altíssima qualidade (Ultra Grade). Textura rugosa e cores multitonais magníficas.',
        price: 1490.00, min_quantity: 1, category_id: '1', status: 'active', featured: false, tag: 'Ultra',
        production_time: 'Pronta Entrega', click_count: 28, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        category: undefined,
        images: [MOCK_IMAGES[18]],
    },
];

// Associar categorias aos produtos
MOCK_PRODUCTS.forEach(p => {
    p.category = MOCK_CATEGORIES.find(c => c.id === p.category_id);
});
